version: '3'
services:
    server:
        image: aic_server_image
        volumes:
          - {{ graphic_log }}:/game/graphic.log:rw
          - {{ server_game_config }}:/game/config.zip:ro
          - {{ server_log }}:/game/server_view.log:rw
          - {{ server_debug }}:/game/debug.log:rw
        environment:
          - client0_id={{ client1_id }}
          - client0_token={{ client1_token }}
          - client0_name={{ client1_name }}
          - client1_id={{ client2_id }}
          - client1_token={{ client2_token }}
          - client1_name={{ client2_name }}
          - client2_id={{ client3_id }}
          - client2_token={{ client3_token }}
          - client2_name={{ client3_name }}
          - client3_id={{ client4_id }}
          - client3_token={{ client4_token }}
          - client3_name={{ client4_name }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '3G'
    client1:
        image: aic_client_image
        volumes:
            - {{ client1_code }}:/game/client.zip:ro
            - {{ client1_log }}:/game/clinet.log
        depends_on:
            - server
        environment:
            - token={{ client1_token }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
    client2:
        image: aic_client_image
        volumes:
            - {{ client2_code }}:/game/client.zip:ro
            - {{ client2_log }}:/game/clinet.log
        depends_on:
            - server
        environment:
            - token={{ client2_token }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
    client3:
        image: aic_client_image
        volumes:
            - {{ client3_code }}:/game/client.zip:ro
            - {{ client3_log }}:/game/clinet.log
        depends_on:
            - server
        environment:
            - token={{ client3_token }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
    client4:
        image: aic_client_image
        volumes:
            - {{ client4_code }}:/game/client.zip:ro
            - {{ client4_log }}:/game/clinet.log
        depends_on:
            - server
        environment:
            - token={{ client4_token }}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'