version: '3'
services:
    compile:
        image: aic_{{ language }}_image
        volumes:
           - {{ code_zip }}:/compile/code.zip:ro
           - {{ code_compiled_zip }}:/compile/compiled/compiled.zip:rw
           - {{ code_log }}:/compile/log/status.log:rw
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
